### ISSUE TITLE
Guidance on passing functions to `props` with `react-wrapper`

### ISSUE THREAD

**Issue by wilson-webdev** [bubblydoo/angular-react#1]
Hello! I am trying to get my head around how I can add callback functions to the `react-wrapper` component. I have the following:

```html
<react-wrapper [component]="MuiButton" [props]="{ color: 'secondary' }">Click me!</react-wrapper>
```

It seems like I should be able to add something like `onClick: doSomething` like so:

```html
<react-wrapper [component]="MuiButton" [props]="{ color: 'secondary', onClick: doSomething }">Click me!</react-wrapper>
```

But that doesn't appear to work. Some guidance would be great!

**Comment by hansottowirtz** [comment]
Hi! I tried it myself and it works for me:

```tsx

import Button from '@mui/material/Button';

@Component({
  template: `<react-wrapper
    [component]="Button"
    [props]="{ onClick }"
  >{{message}}</react-wrapper>`,
})
class MessageComponent {
  Button = Button;

  message = "hi!";

  onClick() {
    console.log("clicked");
  }
}
```

If you're sure something is wrong, could you make a full reproduction?

**Comment by wilson-webdev** [comment]
I've realised what I needed to do when I was referencing `this` within the method I was calling. In this instance you need `.bind(this)`, brings me back to React class components. Maybe a couple of notes in the README would help clear this up.

```ts
import Button from '@mui/material/Button';

@Component({
  template: `<react-wrapper
    [component]="Button"
    [props]="{ onClick: doSomething }"
  >{{message}}</react-wrapper>`,
})
class MessageComponent {
  constructor() {
    this.doSomething = this.doSomething.bind(this);
  }

  Button = Button;
  message = "hi!";

  doSomething() {
    console.log("doing something");
    this.doSomethingElse();
  }

  doSomethingElse() {
    console.log('doing other things');
  }
}
```

**Comment by hansottowirtz** [comment]
This is indeed an issue and I've also noticed it in my components. You can do the following to bind `this`:

```
doSomething = () => {
  console.log("doing something");
}
```

The arrow function will bind `this` automatically. I will update the README.
